### ISSUE TITLE
Issue installing under conda

### ISSUE THREAD

**Issue by djr2015** [facebookresearch/videoseal#13]
Hello, I'm excited by this work and to get it running but am having issues doing so with conda.

How to reproduce:

```
# Create conda environment with python 3.10
conda create -n vseal python=3.10
# Activate conda environment
conda activate vseal

cd videoseal
pip install -e .
```

When running pip install -e . I get
```
Obtaining file:///home/djrob/videoseal
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "/home/djrob/vs/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/djrob/vs/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/djrob/vs/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 181, in prepare_metadata_for_build_editable
          return hook(metadata_directory, config_settings)
        File "/var/tmp/pip-build-env-u2dpc35w/overlay/lib/python3.10/site-packages/flit_core/buildapi.py", line 49, in prepare_metadata_for_build_wheel
          metadata = make_metadata(module, ini_info)
        File "/var/tmp/pip-build-env-u2dpc35w/overlay/lib/python3.10/site-packages/flit_core/common.py", line 453, in make_metadata
          md_dict.update(get_info_from_module(module, ini_info.dynamic_metadata))
        File "/var/tmp/pip-build-env-u2dpc35w/overlay/lib/python3.10/site-packages/flit_core/common.py", line 229, in get_info_from_module
          docstring, version = get_docstring_and_version_via_import(target)
        File "/var/tmp/pip-build-env-u2dpc35w/overlay/lib/python3.10/site-packages/flit_core/common.py", line 202, in get_docstring_and_version_via_import
          spec.loader.exec_module(m)
        File "<frozen importlib._bootstrap_external>", line 883, in exec_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "/home/djrob/videoseal/videoseal/__init__.py", line 9, in <module>
          from .utils.cfg import setup_model_from_model_card as load
        File "/home/djrob/videoseal/videoseal/utils/cfg.py", line 18, in <module>
          from videoseal.augmentation import get_validation_augs
      ModuleNotFoundError: No module named 'videoseal'
      [end of output]
```

I've also tried installing the pytorch related dependencies first, as well as doing this under a `venv` but get the same error in both cases.

**Comment by djr2015** [comment]
Edit: Seems like it might be the same issue as https://github.com/facebookresearch/videoseal/issues/8. 
I saw since https://github.com/facebookresearch/videoseal/pull/7 pip was preferred over conda but I still ran into issues with using `pip` on its own in a different environment.

**Comment by AreChen** [comment]
The same issue was tried on both Linux (Ubuntu) and Windows.

**Comment by AreChen** [comment]
Solved
You need to modify the following line in **videoseal\models\extractor.py**

```
from ..modules.convnext import ConvNeXtV2
from ..modules.hidden import HiddenDecoder
from ..modules.pixel_decoder import PixelDecoder
from ..modules.vit import ImageEncoderViT
```

You need to modify the following line in **videoseal\utils\cfg.py**

```
from ..augmentation import get_validation_augs
from ..augmentation.augmenter import get_dummy_augmenter
from ..data.datasets import (CocoImageIDWrapper, ImageFolder,
                                     VideoDataset)
from ..models import Videoseal, build_embedder, build_extractor, build_baseline
from ..modules.jnd import JND
from ..utils.data import Modalities, parse_dataset_params
```

You need to modify the following line in **videoseal\__init__.py**

```
# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.
"""
Videoseal Package

Videoseal is a package,write anything here.
"""
__version__ = "0.1"

from .utils.cfg import setup_model_from_model_card as load

```

Then `pip install -e .`

**Comment by xiaoyao9184** [comment]
I think the pyproject.toml file is meaningless for packages that are not published to PyPI.

**Comment by cdluminate** [comment]
This issue persists. The fix mentioned by people above is precisely the follows:

```patch
diff --git a/videoseal/__init__.py b/videoseal/__init__.py
index c197183..8d19b48 100644
--- a/videoseal/__init__.py
+++ b/videoseal/__init__.py
@@ -3,7 +3,11 @@
 #
 # This source code is licensed under the license found in the
 # LICENSE file in the root directory of this source tree.
+"""
+Videoseal Package
 
+Videoseal is a package,write anything here.
+"""
 __version__ = "0.1"
 
 from .utils.cfg import setup_model_from_model_card as load
diff --git a/videoseal/models/extractor.py b/videoseal/models/extractor.py
index ae16730..9986f96 100644
--- a/videoseal/models/extractor.py
+++ b/videoseal/models/extractor.py
@@ -5,10 +5,10 @@
 
 import torch
 from torch import nn
-from videoseal.modules.convnext import ConvNeXtV2
-from videoseal.modules.hidden import HiddenDecoder
-from videoseal.modules.pixel_decoder import PixelDecoder
-from videoseal.modules.vit import ImageEncoderViT
+from ..modules.convnext import ConvNeXtV2
+from ..modules.hidden import HiddenDecoder
+from ..modules.pixel_decoder import PixelDecoder
+from ..modules.vit import ImageEncoderViT
 
 
 class Extractor(nn.Module):
diff --git a/videoseal/utils/cfg.py b/videoseal/utils/cfg.py
index a292ec6..18fb3ac 100644
--- a/videoseal/utils/cfg.py
+++ b/videoseal/utils/cfg.py
@@ -14,10 +14,10 @@ import torch
 import torchvision.transforms as transforms
 from omegaconf import DictConfig, OmegaConf
 
-from videoseal.augmentation.augmenter import get_dummy_augmenter
-from videoseal.data.datasets import CocoImageIDWrapper, ImageFolder, VideoDataset
-from videoseal.models import Videoseal, build_embedder, build_extractor, build_baseline
-from videoseal.modules.jnd import JND
+from ..augmentation.augmenter import get_dummy_augmenter
+from ..data.datasets import CocoImageIDWrapper, ImageFolder, VideoDataset
+from ..models import Videoseal, build_embedder, build_extractor, build_baseline
+from ..modules.jnd import JND
 
 omegaconf.OmegaConf.register_new_resolver("mul", lambda x, y: x * y)
 omegaconf.OmegaConf.register_new_resolver("add", lambda x, y: x + y)
@@ -253,4 +253,4 @@ def setup_dataset(args):
                 transform = resize_short_edge
             )  
         print(f"Image dataset loaded from {dataset_config.val_dir}")
-    return dataset
\ No newline at end of file
+    return dataset
```
